### ISSUE TITLE
Debian 11 fresh install problem

### ISSUE THREAD

**Issue by ecsuae** [bepasty/bepasty-server#284] opened 2023-01-21 15:47 UTC
I have followed the documentation and login page works fine, as soon I create a paste I get error in browser:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

in server I see in logs:
```
[2023-01-21 15:44:18,855] ERROR in app: Exception on /LTKP3NFE [GET]
Traceback (most recent call last):
  File "/home/bepasty/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bepasty/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bepasty/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bepasty/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bepasty/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/bepasty/lib/python3.9/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/home/bepasty/repo/src/bepasty/views/display.py", line 129, in get
    rendered_content = Markup(highlight(text, lexer, formatter))
  File "/home/bepasty/lib/python3.9/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/bepasty/lib/python3.9/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/home/bepasty/lib/python3.9/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/bepasty/repo/src/bepasty/utils/formatters.py", line 43, in format_unencoded
    source = self.wrap(source, outfile)
TypeError: wrap() takes 2 positional arguments but 3 were given
```
**Please. guide what's wrong and how to fix it.**

**Comment by ThomasWaldmann** [comment] 2023-01-21 16:47
Duplicate of #281, closing.

**Closed by ThomasWaldmann** 2023-01-21 16:47 UTC
