### ISSUE TITLE
Fallback to / after login, no redirect to hash 

### ISSUE THREAD

**Issue by Marwe** [bepasty/bepasty-server#212] opened 2020-05-03 23:31 UTC
Currently, the link/hash to an item gets lost after logging in.

To reproduce: if someone

* requests https://server/hash
* and gets "Forbidden" (not logged in, no read permissions) 
* then logs in
* is thrown/redirected to https://server/
* you have to navigate your browser with the back button or re-paste/click the URL

Expected behaviour is:

* to reach page https://server/hash directly after login

It used to be like that in earlier versions.

It might be a configuration issue on my side, though I did not change too much in the config.
Checked the config, but there were only minimal changes between versions.

**Comment by ThomasWaldmann** [comment] 2020-05-04 13:54
yeah, of course it should stay at same URL after login.

**Comment by ThomasWaldmann** [comment] 2020-10-31 21:43
I tried with the current code from master and it behaves like desired.

First got "you're not allowed", then logged in with a password, then got back to same URL and got the normal item display of same item.

So, I can't reproduce - can you @Marwe ?

**Comment by ThomasWaldmann** [comment] 2020-11-07 23:14
No reply, closing.

**Closed by ThomasWaldmann** 2020-11-07 23:14 UTC
Labels: question
